### ISSUE TITLE
problem to get the tool running

### ISSUE THREAD

**Issue by Jonathan003** [zcesur/opening-repertoire#2]
Hi,
I have a big interest in chess software development but I'm a total newbie when it comes to programming.
I tried you command line tool with the example pgn file ' ericrosen-white.pgn' that comes with the download.
If I type in command prompt:

> opening-repertoire -p C:\Users\Jonathan\Downloads\Chess\opening-repertoire-master\data\ericrosen-white.pgn -c white -s e4,c5

I get this error message:

> thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `65536`,
 right: `16384`', C:\Users\Jonathan\.cargo\registry\src\github.com-1ecc6299db9ec823\pgn-reader-0.15.0\src\reader.rs:553:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I probably do sommeting wrong?

**Comment by Jonathan003** [comment]
I made a video capture of my attempt to run the app. I use a windows 10 64 bit system with the latest updates.

https://user-images.githubusercontent.com/40061628/103103764-b5a19f80-4623-11eb-8ddc-2daf08d364fe.mp4

**Comment by zcesur** [comment]
Hi! The problem you are having seems to be rooted in a library we depend on: niklasf/rust-pgn-reader#17

I pinned the version to a commit that hopefully fixes this issue. Why don't you reinstall opening-repertoire, give it another go and let me know how it goes!

**Comment by Jonathan003** [comment]
It looks like it works now. I don't get any error messages.
That's great! I look for a long time for a tool like this. If you have to do this manually it takes a very long time. There will always be need for some manual tuning of a repertoire, but this helps allot.
Where can a find the resulting pgn with the repertoire?
Do I have to copy the text in the command line window?
I'm count of new to GitHub, I don't know exactly how everything works. I have many ideas for  additional functions to your great repertoire making tool. I will post them here.

**Comment by Jonathan003** [comment]
I have tree request for future updates. 
1.	For the option (-s, --starting-moves <STRING>    Filter games by some comma-separated starting moves, e.g. 'e4,c5') I would like to have some additional options. I would like to use different strings at the same time by using ‘;’. Then for example 'e4,c5;e4,e5’ would create a repertoire for the Sicilian as well for the Double King’s pawn opening. Or ‘e4;d4;c4;Nf3’ would create a repertoire for these 4 white first moves.
2.	I would like to have some options to build wider repertoires. For the moment the result has only one candidate move for the side of the repertoire. I would like to have 5 options, 1: to build a narrow repertoire like it is now, 2: to build a wider repertoire where the top main lines are included, 3: to build a wide repertoire where all main lines are included. 4: to build a repertoire where also sidelines are included. And 5: to build a repertoire where all lines are included except very rare lines that are almost never played. 
And at the same time, I want to set these options independently for the other color. For example, if make a repertoire for white, I want to use option 2 for the white candidate moves, and option 4 for the black candidate moves. 
3.	I want an option to filter games according to my repertoire. Say I made a white repertoire based on the games of some model Grandmaster which playing style I like. But I can only find 2000 games in databases where he plays white. So obviously there will be many holes in the repertoire. 
So, I make a second white repertoire from a huge pgn database with hundreds of thousands of games, where one of the players have a rating of +2400 Elo. The games of this model Grandmaster are also included in this huge pgn database. Now I have this second white repertoire. I want to filter this second repertoire so I get only the variations that can arise after playing the opening lines from the first repertoire. So also, the replies for white will be included when black deviates from the lines in the first repertoire. I basically want to do what’s described here: http://wbec-ridderkerk.nl/html/details1/PolyGlot.html
Under the title book merging. 
I can import the best moves from the merged bin books to Opening Lines in Lucas Chess, and then export to pgn.
But I want to be able to do this directly with pgn games. There is some weird explosion of number of games if I use Lucas Chess for this.

**Comment by zcesur** [comment]
I'm glad that you find it helpful!

I'm not a Windows user but AFAIK you should be able to redirect the output of the program into a file by adding `> filename.pgn` at the end of the command. It should create (or overwrite) a file inside the folder where you run the command. Something like

```
opening-repertoire -p input.pgn -c white > output.pgn
```

**Comment by zcesur** [comment]
I'm glad you found it helpful!

I'm not a Windows user but AFAIK you should be able to redirect the output of the program into a file by adding `> filename.pgn` at the end of the command. It should create (or overwrite) a file inside the folder where you run the command. Something like

```
opening-repertoire -p input.pgn -c white > output.pgn
```

**Comment by zcesur** [comment]
I'm glad that you find it useful!

I'm not a Windows user but AFAIK you should be able to redirect the output of the program into a file by adding `> filename.pgn` at the end of the command. It should create (or overwrite) a file inside the folder where you run the command. Something like

```
opening-repertoire -p input.pgn -c white > output.pgn
```

**Comment by zcesur** [comment]
I'm glad you found it useful!

I'm not a Windows user but AFAIK you should be able to redirect the output of the program into a file by adding `> filename.pgn` at the end of the command. It should create (or overwrite) a file inside the folder where you run the command. Something like

```
opening-repertoire -p input.pgn -c white > output.pgn
```

**Comment by Jonathan003** [comment]
Yes this works to save the output as pgn on windows to. Thanks for the tip.
This issue can be closed I think? I'm not sure how this works? Do I have to close it or do you close it?

**Comment by zcesur** [comment]
Feel free to close an issue if you feel like it has been resolved!
