### ISSUE TITLE
not the main line error 

### ISSUE THREAD

**Issue by Jonathan003** [zcesur/opening-repertoire#3]
I tried you tool with the games I find of Magnus Carlsen on lichess.org and in the Megadatabase from Chessbase.  I tried it with the game where Magnus plays white.
If I open the pgn database with SCID I can see in the tree window, that the main line he plays is 1.e4
![image](https://user-images.githubusercontent.com/40061628/103136375-1ed6f080-46c0-11eb-9de0-f88557f18f22.png)
If I use your tool and I type this in the command window: `opening-repertoire -p C:\Users\Jonathan\Downloads\Chess\opening-repertoire-master\data\Carlsen_white.pgn -c white`
I get only the lines after 1.Nc3 and this is not the main line, in fact it is only a rare played line.
I include the database of Magnus Carlsen's white games in the attachment so you can check for yourself.
[Carlsen_white.zip](https://github.com/zcesur/opening-repertoire/files/5742038/Carlsen_white.zip)

**Comment by zcesur** [comment]
Ah, thanks for reporting this. I know why this is happening.

**Comment by zcesur** [comment]
Should be resolved now

**Comment by Jonathan003** [comment]
It looks great!
Thanks for the quick fix.

**Comment by vesper8** [comment]
@zcesur Now that you've added support for multiple roots, can we safely assume that the first root will always be the most popular (most commonly played) ? That's how I would like it / expect it to be since that is also the case for root children

**Comment by zcesur** [comment]
Neither the roots nor the children are sorted by popularity, so no, you may not assume that.

On the other hand, if pruning is enabled, there will be at most 1 move for each of the opponent moves, and that move is guaranteed to be the most popular one.

**Comment by vesper8** [comment]
@zcesur thank you for your response : )

I didn't notice the warning about pruning.. but now I see that pruning is enabled by default and so unless I am specifically running the command with `--disable-pruning`, which I am not, then in this case I can assume that the first move will be the most popular

This is the type of command I am running, in which case I would like to be able to assume that the first root, and the first child, will always contain the most commonly played move

```
opening-repertoire --path storage/app/public/pgn/exported/EricRosen/white.pgn --color white --starting-moves d4,d5,Bf4,Nc6 --output-type json --max-moves 10 --inode-max-depth 8
```

**Comment by zcesur** [comment]
It depends on the move color. Since you selected `--color white`, each leftmost white node will be the most commonly played move, since all of its siblings are pruned out. On the other hand, each leftmost black node may or may not be the most commonly played move.
