### ISSUE TITLE
Three request for future updates for opening-repertoire tool.

### ISSUE THREAD

**Issue by Jonathan003** [zcesur/opening-repertoire#4]
1.	For the option (-s, --starting-moves <STRING>    Filter games by some comma-separated starting moves, e.g. 'e4,c5') I would like to have some additional options. I would like to use different strings at the same time by using ‘;’. Then for example 'e4,c5;e4,e5’ would create a repertoire for the Sicilian as well for the Double King’s pawn opening. Or ‘e4;d4;c4;Nf3’ would create a repertoire for these 4 white first moves. In addition it would be nice to be able to use short algebraic notation for the strings. For example '1.e4 e5;1.e4 e5’ or '1.e4;1.d4;1.c4;1.Nf3'

2.	I would like to have some options to build wider repertoires. For the moment the result has only one candidate move for the side of the repertoire. I would like to have 5 options, 1: to build a narrow repertoire like it is now, 2: to build a wider repertoire where the top main lines are included, 3: to build a wide repertoire where all main lines are included. 4: to build a repertoire where also sidelines are included. And 5: to build a repertoire where all lines are included except very rare lines that are almost never played. 
And at the same time, I want to set these options independently for the other color. For example, if make a repertoire for white, I want to use option 2 for the white candidate moves, and option 4 for the black candidate moves. And if I don’t set an option for the black candidate moves, I want all candidate moves for black to be included, like it is now.
3.	I want an option to filter games according to my repertoire. Say I made a white repertoire based on the games of some model Grandmaster which playing style I like. But I can only find 2000 games in databases where he plays white. So obviously there will be many holes in the repertoire. 
So, I make a second white repertoire from a huge pgn database with hundreds of thousands of games, where one of the players have a rating of +2400 Elo. The games of this model Grandmaster are also included in this huge pgn database. Now I have this second white repertoire. I want to filter this second repertoire so I get only the variations that can arise after playing the opening lines from the first repertoire. So also, the replies for white will be included when black deviates from the lines in the first repertoire. I basically want to do what’s described here: http://wbec-ridderkerk.nl/html/details1/PolyGlot.html
Under the title book merging. 
I can import the best moves from the merged bin books to Opening Lines in Lucas Chess, and then export to pgn.
But I want to be able to do this directly with pgn games. There is some weird explosion of number of games if I use Lucas Chess for this.

**Comment by zcesur** [comment]
Thanks for the suggestions! I built this tool as a fun weekend project and I'm not actively developing it, but I might implement some if not all of these in the future.

For building wider repertoires, you might find `--disable-pruning` option helpful, which enables all lines.

**Comment by zcesur** [comment]
By the way, it'd be great if you could post each feature request in its own issue next time! That way they are easier to track and manage for me.

**Comment by Jonathan003** [comment]
A weekend project? Is it really that easy for you to create a tool I'm looking for the past 10 years.
I wil split the enhancement issue in three. 
Can I or you see somewhere if an issue commend is edited, sinds we last read it? Probably not we can just see when it was last edited. I ask this because I sometimes change sommeting to my post. And I want to make sure that you have read it.

**Comment by Jonathan003** [comment]
If I use the option `--disable-pruning` and all variations are there. What can be the use of it for making repertoires?

**Comment by zcesur** [comment]
:-)

Nope, I'm not notified of your edits.

> If I use the option `--disable-pruning` and all variations are there. What can be the use of it for making repertoires?

Isn't that more or less what you described in the 5th option?

**Comment by Jonathan003** [comment]
> Isn't that more or less what you described in the 5th option?

I'm planning to study opening repertoires over several years.
I would only use this option for the other collar. If I make a repertoire for white a would use the option for the black candidates. I would for example first make a white repertoire and use option 2 for the white candidate moves, and option 3 for the black candidate moves. Then when I have studied the repertoire. I would make the repertoire again and use option 2 for the white candidate moves, and option 4 for the black candidate moves. End finally when I have studied this repertoire, I would make the repertoire again and use option 2 for the white candidate moves, and option 5 for the black candidate moves. These are just some examples how I would use the different options.

**Comment by Jonathan003** [comment]
If I use the option `--disable-pruning` is this the same as the 5th option of my request? Or wil very rare lines that are almost never played, still be included for both white and black?

**Comment by zcesur** [comment]
Those lines will also be included, yes.

**Comment by zcesur** [comment]
Closing this now that there is a separate issue for each feature.
