### ISSUE TITLE
A lot of doubles in output.pgn

### ISSUE THREAD

**Issue by Jonathan003** [zcesur/opening-repertoire#8]
There are a lot of doubles in the resulting repertoire pgn output. It are opening lines that are included in other longer opening lines. I would prefer it if these short doubles would not be included in the output.

![image](https://user-images.githubusercontent.com/40061628/103139682-ec88bb80-46de-11eb-99b3-788f9e177f9d.png)

**Comment by zcesur** [comment]
This is actually meant to be a feature. My intention with including these shorter lines was to split the PGN into groups of lines so that there are small, organized chunks that are easier to digest.

You can use the option `-d` or `--inode-max-depth` to control the granularity of groups. It is 8 by default, which means that all shorter lines up to 8 plies are included. You can set it to 0 to disable this feature entirely.

**Comment by Jonathan003** [comment]
> My intention with including these shorter lines was to split the PGN into groups of lines so that there are small, organized chunks that are easier to digest.

That's an interesting idea! You mean by searching the pgn for these short duplicated games? And then train these lines.
How exactly can I short out these lines? Because many time these shorter double lines are not much shorter than the other lines.
Maybe it can be done by searching for duplicates in SCID?

**Comment by zcesur** [comment]
Hmm not quite what I had in mind. Let me show you how I mentally parse the output in your screenshot:

## 1...g6 (1. Nc3 g6 2. d4)
### 2...Bg7 (1. Nc3 g6 2. d4 Bg7 3. Nc3)
##### 3...c5 (1. Nc3 g6 2. d4 Bg7 3. Nc3 c5 4. Be3)
- `1. Nc3 g6 2. d4 Bg7 3. Nc3 c5 4. Be3 cxd4 5. Bxd4 Nf6 6. e5 Nh5 7. Nh3 d6 8. g4 Nf4 9. Nxf4 dxe5 10. Be3`
##### 3...c6 (1. Nc3 g6 2. d4 Bg7 3. Nc3 c6 4. Nf3)
- `1. Nc3 g6 2. d4 Bg7 3. Nc3 c6 4. Nf3 d5 5. h3 Nh6 6. Bd3 dxe4 7. Nxe4 Nf5 8. c3 Nd7 9. O-O O-O 10. Bf4`
- `1. Nc3 g6 2. d4 Bg7 3. Nc3 c6 4. Nf3 d5 5. h3 dxe4 6. Nxe4 Nf6 7. Nxf6+ exf6 8. Bc4 O-O 9. O-O Re8 10. Re1`
##### 3...b6 (1. Nc3 g6 2. d4 Bg7 3. Nc3 b6 4. Be3)
- `1. Nc3 g6 2. d4 Bg7 3. Nc3 b6 4. Be3 Bb7 5. Qd2 e6 6. h4 h6 7. f3 d6 8. O-O-O Nd7 9. g4 a6 10. Bd3`
##### 3...d6 (1. Nc3 g6 2. d4 Bg7 3. Nc3 d6 4. Be3)
- `1. Nc3 g6 2. d4 Bg7 3. Nc3 d6 4. Be3 Nf6 5. h3 Nc6 6. f4 O-O 7. Nf3 e5 8. fxe5 dxe5 9. d5 Nd4 10. Bd3`
- `1. Nc3 g6 2. d4 Bg7 3. Nc3 d6 4. Be3 Nf6 5. h3 c6 6. Nf3 Qa5 7. Bd3 b5 8. O-O b4 9. Ne2 O-O 10. Ng3`
### 2...Nf6 (1. Nc3 g6 2. d4 Nf6 3. Nc3)
##### 3...Bg7 (1. Nc3 g6 2. d4 Nf6 3. Nc3 Bg7 4. e4)
- `1. Nc3 g6 2. d4 Nf6 3. Nc3 Bg7 4. e4 d6 5. Be2 O-O 6. O-O Bg4 7. Be3 Nc6 8. Qc1 e5 9. dxe5 dxe5 10. Rd1`

So essentially you can think of these shorter lines as chapters and sub-chapters. For example you can dedicate one day to studying 2...Bg7 and another day to 2...Nf6. I find that breaking up the output like this makes it easier for me to categorize lines in my brain.

**Comment by Jonathan003** [comment]
I understand, this looks very useful!
I use Hiarcs Chess Explorer to split the PGN into groups . In the option Player Explorer, Information tab view, you can see the different  openings a player played sorted by opening names, (you can always create fictive player names in the pgn with a text editor to make this function work) . And you can export these different  openings to separate pgn's. I also further divide the openings by the 'collect openings' option in Chessbase 15. This create even more deviated openings, (there is only a problem that not all variations are in the resulting merged games, some lines are missing).
Therefor I create different openings in the android app Chess Trainer Pro: https://play.google.com/store/apps/details?id=com.ayelmarc.chessormpro&hl=en_US&gl=US
I first make the openings divided by Hiarcs Chess Explorer. Than I also create these smaller openings divided by Chessbase 15. I start by studying these smaller openings.
I can imagine if you are a programmer you want to build your ow software and use this instead.

**Comment by zcesur** [comment]
I see, nice! I must admit I don't use any chess software other than a couple web apps like lichess and chessable, and I only play casually online, but it sounds like you are very devoted to studying openings. :) Out of curiosity, do you play competitive OTB chess? Are you rated 2k+?

**Comment by Jonathan003** [comment]
No, I'm 41 years old, and I started to play chess only when I was 23 years old or something. I'm playing at a chess club here in Gent in Belgium. I'm only rated about 1400, and my best online rating on chess.com is 1600. But I have a lot of ambition to improve. Everybody can dream right? The funny fact is that I actually didn't study many openings yet. I just spend many hours looking for best ways to create repertoires. This is very time consuming with existing chess software. I have a big interest in the development of new chess software, and I think there still is a lot off potential for improvement. Especially for chess software that helps chess players to become better players. Like the repertoire building tool, you are making. Too bad I'm not a programmer myself. What about you, what's you online rating if I may know?

**Comment by zcesur** [comment]
Nice, keep at it! It's awesome that you're part of a chess community; I wish to join a chess club at some point, too.

I went down the rabbit hole of building an opening repertoire myself and I totally know what you mean. Eventually I settled down with a rather simple repertoire and focused more on learning general ideas behind my openings rather than committing deep, concrete lines to memory. This allowed me to devote more time to solving tactics and studying middlegame strategy, and I think my game has improved a lot more as a result of that. What worked for me may not work for you, but I thought I'd share my experience!

My lichess rating is 1900-2100 depending on the time control, though I have a feeling that ratings are very inflated there. I suppose my real rating would be a lot lower than that.

**Comment by Jonathan003** [comment]
My rating on lichess.org is 1800. I have read that compared to chess.com there is usually a difference of about 200 Elo points. The rating on chess.com is more realistic.

**Comment by zcesur** [comment]
I'll take your word for it

**Comment by zcesur** [comment]
Closing this now that you know how to get rid of these "doubles".
